### ISSUE TITLE
Add other currencies' faucet

### ISSUE THREAD

**Issue by ghost** [XRPLF/xrpl-py#259]
Add other currencies' faucet in **xrpl-py** as functions,

faucets such as BTC, USD, EUR and ETH 

```
xrpl.wallet.btc_faucet
xrpl.wallet.usd_faucet
xrpl.wallet.eur_faucet
xrpl.wallet.eth_faucet
```

This will increase liquidity on the testnet's DeX and enables developers to test Funds and the DeX.

**Comment by ledhed2222** [comment]
good idea. want to make a pull request for this @wojakkk?

**Comment by wojakkk** [comment]
Here's my suggestion,

To maximize the experience of using the mainnet while being in the testnet, we should all agree to use the same currency with the same issuer so that they are liquidity on the buy/sell side on the DeX (I suggest using  XRPL Labs' issuing address) , XRPL Labs should develop a faucet for their currencies on the testnet so the developers could utilize their currencies to test their applications (BTC/ETH/USD/EUR), I can't make a pull request since I don't have the private key to the issuing address. Sorry.

@WietseWind

**Comment by WietseWind** [comment]
@wojakkk I don't think this will be developed by XRPL Labs: we're pretty busy developing a lot of other things at the moment. However, @hammertoe already said he'd be looking into this, and @yyolk also mentioned building something if no one else would.

**Comment by ledhed2222** [comment]
In the meantime, you can always have two wallets yourself and issue currency from one

**Comment by ledhed2222** [comment]
adding more on this, just in case it's not clear @wojakkk, here is how you can issue currency with this library from one wallet to another. following this process will allow you to test cross-currency payments fully in testnet without any faucet support. having a faucet for issued currencies would definitely be useful, but it doesn't stop you from exploring the functionality :)

at a high level, the steps for issuing currency from wallet A to wallet B are:

1. create a trust line from wallet B to wallet A
2. send a payment of the issued currency from wallet A to wallet B

the process is described here: https://xrpl.org/issued-currencies-overview.html#issued-currency-properties


```python
from xrpl.account import get_next_valid_seq_number
from xrpl.clients import JsonRpcClient
from xrpl.models.amounts import IssuedCurrencyAmount
from xrpl.models.transactions import Payment, TrustSet
from xrpl.transaction import safe_sign_and_submit_transaction
from xrpl.wallet import Wallet

CLIENT = JsonRpcClient(url)

# create issuing wallet and set its sequence number
ISSUING_WALLET = Wallet(ISSUER_SEED, 0)
ISSUING_WALLET.sequence = get_next_valid_seq_number(
  ISSUING_WALLET.classic_address,
  CLIENT,
)

# create receiving wallet and set its sequence number
RECEIVING_WALLET = Wallet(RECEIVER_SEED, 0)
RECEIVING_WALLET.sequence = get_next_valid_seq_number(
  RECEIVING_WALLET.classic_address,
  CLIENT,
)

# create a trust line from receiver to issuer. in this case, 
# the receiver trusts the issuer for up to $1,000,000 USD
safe_sign_and_submit_transaction(
  TrustSet(
    account=RECEIVING_WALLET.classic_address,
    sequence=RECEIVING_WALLET.sequence,
    limit_amount=IssuedCurrencyAmount(
      issuer=ISSUING_WALLET.classic_address,
      currency="USD",
      value="1000000",
   ),
  RECEVING_WALLET,
  CLIENT,
)

# increment the sequence number of the receiver
RECEIVING_WALLET.sequence += 1

# now, issue some USD from issuer to receiver
safe_sign_and_submit_transaction(
  Payment(
    account=ISSUING_WALLET.classic_address,
    sequence=ISSUING_WALLET.sequence,
    amount=IssuedCurrencyAmount(
      issuer=ISSUING_WALLET.classic_address,
      currency="USD",
      value="100",
    ),
    destination=RECEIVING_WALLET.classic_address,
  ),
  ISSUING_WALLET,
  CLIENT,
)

# finally increment sequence number for issuer, since we did a transaction
ISSUING_WALLET.sequence += 1
```

**Comment by wojakkk** [comment]
@ledhed2222 Cool! Thanks. 
.
@WietseWind @hammertoe 

What I am trying to recommend/achieve is to create a standard testnet currency (USD,EUR,BTC,ETH) where all the developers could test their applications whilst using these standard currencies, developers using the same currency in the testnet would enhance application testing, DeX testing, cross-currency testing, etc...

To achieve this, we could start normalizing using a faucet with the same issuer via XRPL Labs' issuing address and add it to [https://xrpl.org/xrp-testnet-faucet.html](url)

**Comment by yyolk** [comment]
Definitely simmering this in the background, wanted to break it down a bit.

My initial thought was to just create orders and cancel them every hour/24h in a simple way. Seemed easy enough, just create random orders on both sides.

On Tuesday, I liked @intelliot's suggestion of syncing the orders from mainnet to the testnet. This would ultimately get out of sync, and it could be handled by cleaning up similarly to how I was thinking with the naive approach (closing all orders and re-opening, with the current state of the main net).
We couldn't force anyone who have opened offers themselves, to close them but I don't think it would be such a big deal. There would probably be some troubleshooting and feedback from everyone if closing those open orders mess up anything they're trying to do. The drop everything and re-sync seems to be the easiest way to keep it mimicking the mainnet.


For some minor implementation details, David also mentioned on Tuesday one could take the orders from the mainnet using `book_offers` (and I think the relevant `xrpl.models.requests.BookOffers` within xrpl-py context) which could be mapped in a straight forward way into a bunch of `OfferCreates` (`xrpl.models.transactions.OfferCreate`) with the 'testnet issuers' that are set up for those issued currencies. Tapping both all USD issuers on mainnet for instance could give us even more orders for testing but one is sufficient for the first release. 

<details><summary>book offers context</summary>

via: https://xrpl.org/websocket-api-tool.html#book_offers
![image](https://user-images.githubusercontent.com/134478/122610664-a1c07e80-d045-11eb-9660-579308ce482b.png)

</details> 


In my opinion, and the other part of this issued currency faucet is that I would want to easily request the issued currency on the testnet for any testnet user/developer to grab and subsequently use.

I think this is as easy as instructing the user/developer to set a trust line to the issuer, and then an API call to request an issuance to the developer's testnet address. 

This could be a developer tool page like https://xrpl.org/tx-sender.html which walk you through the steps.

Since the page just uses API calls underneath (i.e. https://xrpl.org/xrp-testnet-faucet.html which let's you grab an address easily with an HTTP POST
![image](https://user-images.githubusercontent.com/134478/122609152-2958be00-d043-11eb-91fa-01c313c5c659.png).)

The only difference would be POST'ing a valid testnet address that has also created a trust line prior. 
This shouldn't be too bad, an error message in case the developer forgot to set they can get the instructions to do so in the message if they're interacting with it through HTTP POST directly.

So nothing to show off yet, but I think it's straight forward if useful for others (vs spinning up your own issued currency and market orders following the same path, just make it available so there's less friction in testing these cool features on XRPL).
