### ISSUE TITLE
XRPL Constants - 4 letter/digit issued currencies not supported (DGE-66)

### ISSUE THREAD

**Issue by ciouz** [XRPLF/xrpl-py#292]

**Comment by JST5000** [comment]
Hey @ciouz, in order to set up a 4 character issued currency, you'll want to create a [non-standard currency code](https://xrpl.org/currency-formats.html#nonstandard-currency-codes)

You'll have to encode your currency code into hex yourself, but this code snippet should help if you're using javascript/typescript :)

```   
    import convertStringToHex from 'xrpl'
    const currencyCode = 'ABCD' // Change this to the currency code you want
    const bytesToEncodeTo = 40
    const encodedCurrencyCode = convertStringToHex(currencyCode).padEnd(
      bytesToEncodeTo,
      '00',
    )

    /*
     * Which will become:
     * '41424344000000000000000000000000000000000000000000000000000000000000000000000000'
     */
 ```

(Note: Since non-standard currency codes' first 8 bits can't be 0x00, it's standard to put your currency code on the left, then 0-pad the rest)

And in case you can't import convertStringToHex, it's just this one liner under the hood:
`Buffer.from(string, 'utf8').toString('hex').toUpperCase()`

Does this address the problem you were dealing with?

**Comment by JST5000** [comment]
Here's a version of that code for Python - 

```
currencyCode = 'ABCD' #Change this to your currency code
bytesToEncodeTo = 40
encodedCurrencyCode = str(bytes(currencyCode, encoding="utf-8").hex()).ljust(bytesToEncodeTo * 2, '0')
print(encodedCurrencyCode)
# Should print 41424344000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by ciouz** [comment]
Hey @JST5000, thanks for your help. This definitely helped with the encoding, but what I am trying to do is transact an issued currency from one address to another in which both have the same trustline.

The encodedCurrencyCode in the example below still throws the error  
xrpl.models.exceptions.XRPLModelException: {'currency': 'Invalid currency 
because I believe it goes back to the Constants script... is there any way around this with hex and the below payment method?

send_token_tx = xrpl.models.transactions.Payment(
        account=account,
        destination=dest_address,
        amount=xrpl.models.amounts.issued_currency_amount.IssuedCurrencyAmount(
            currency=encodedCurrencyCode,
            issuer=issuer_address,
            value=issue_quantity
        ),
)

Thanks so much for your time, truly appreciated!
