### ISSUE TITLE
Add optional `marker` to `get_account_transactions`

### ISSUE THREAD

**Issue by LimpidCrypto** [XRPLF/xrpl-py#426]
The high-level method `get_account_transactions` should have an argument `marker`.
When requesting [`account_tx`](https://xrpl.org/account_tx.html) it is not guaranteed to receive all transactions an account has ever sent at once.
When an account has a transaction history that is too large, the node only sends a part of it, up to an amount it would become inefficient. If that's the case it also sends a [`marker`](https://xrpl.org/markers-and-pagination.html) field to indicate at what Ledger the node has stopped. The user can use it for the next call to tell the node where to start, to receive the next batch of transactions.

For `get_account_transactions` that argument is missing but would be very useful IMO.
If added to `get_account_transactions`, the function `get_account_payment_transactions` should also get that argument.

**Comment by JST5000** [comment]
Closing this as "won't fix" because it's better to just directly use the `AccountTx` request instead of building a helper which does the exact same thing without processing. In a version 2, we should probably remove the `get_account_transactions` sugar function since it doesn't add much to the raw request.
